import { marked } from "marked";
import { generateJSON } from "@tiptap/html";
import StarterKit from "@tiptap/starter-kit";
import Image from "@tiptap/extension-image";
import { nanoBanana } from "../../googleNanoBanana";
import { sharpImageCompress } from "@/lib/imageCompress/sharpImageCompress";
import { uploadImageOnCloudinary } from "@/lib/cloudinary";
import { openaiImage } from "../../openAiImage";

export async function parseAiBlogContent(article_markdown: string) {
  // const images = [...article_markdown.matchAll(/!\[IMAGE:\s*(.*?)\]/g)].map(
  //   (image) => ({
  //     placeholder: image[0],
  //     description: image[1],
  //   }),
  // );

  // genrate with ai and upload images on cloudinary
  // const imagePromises = images.map(async (image) => {
    // const imagebase64 = await openaiImage(image.description);
    
    // if (!imagebase64) {
    //   throw new Error("Image data is null generated by open ai");
    // }
  //    const interation  = await nanoBanana(image.description);
  //    const generatedImage = interation.output_image;

  //    if(!generatedImage || !generatedImage.data){
  //       throw new Error("Nano Banana unable to generate image data");
  //    }

  //   const imageCompress = await sharpImageCompress(generatedImage.data);
  //   const cloudurl = await uploadImageOnCloudinary(imageCompress.toBase64());

  //   if (!cloudurl) {
  //     throw new Error("Failed to upload on cloudinary");
  //   }

  //   return {
  //     ...image,
  //     cloudinaryUrl: cloudurl,
  //   };
  // });
  // console.log("images:", images);
  // const imagesResolvedData = await Promise.all(imagePromises);
  // //
  // for (let imageItem of imagesResolvedData) {
  //   article_markdown = article_markdown.replace(
  //     imageItem.placeholder,
  //     `![${imageItem.description}](${imageItem.cloudinaryUrl})`,
  //   );
  // }
  // console.log("after replace images:", images);
  // console.log("after -> replace:", article_markdown);

  const markedHtml = await marked.parse(article_markdown);
  const content = generateJSON(markedHtml, [StarterKit, Image]);
  return content;
}
